apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telegram-bots

resources:
  - namespace.yaml
  - configmap.yaml
  - redis-deployment.yaml
  - webhook-server-deployment.yaml
  - ai-worker-deployment.yaml
  - image-bot-deployment.yaml
  - admin-bot-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: telegram-bots-platform
