global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'telegram_bots_platform'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webhook_server:8000']
