from .analytics import (
    analytics_router,
    cb_analytics,
    cb_analytics_bots,
    cb_analytics_buttons,
    cb_analytics_commands,
    cb_analytics_errors,
    cb_analytics_generations,
    cb_analytics_live,
    cb_analytics_messages,
    cmd_admin_stats,
)
from .instances import cb_instances_list, instances_router
from .menu import cb_admin_menu, cmd_admin_menu, menu_router
from .presets import (
    cb_preset_del_confirm,
    cb_preset_del_do,
    cb_preset_detail,
    cb_preset_seed,
    cb_preset_toggle,
    cb_presets_list,
    cb_start_add_preset,
    presets_router,
    process_preset_category,
    process_preset_icon,
    process_preset_id,
    process_preset_target_bot,
    process_preset_template,
    process_preset_title,
)

__all__ = [
    "analytics_router",
    "cb_admin_menu",
    "cb_analytics",
    "cb_analytics_bots",
    "cb_analytics_buttons",
    "cb_analytics_commands",
    "cb_analytics_errors",
    "cb_analytics_generations",
    "cb_analytics_live",
    "cb_analytics_messages",
    "cb_instances_list",
    "cb_preset_del_confirm",
    "cb_preset_del_do",
    "cb_preset_detail",
    "cb_preset_seed",
    "cb_preset_toggle",
    "cb_presets_list",
    "cb_start_add_preset",
    "cmd_admin_menu",
    "cmd_admin_stats",
    "instances_router",
    "menu_router",
    "presets_router",
    "process_preset_category",
    "process_preset_icon",
    "process_preset_id",
    "process_preset_target_bot",
    "process_preset_template",
    "process_preset_title",
]
